package com.fruit.manage.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("bus_banner", "id", Banner.class);
		arp.addMapping("bus_classify", "id", Classify.class);
		arp.addMapping("bus_product", "id", Product.class);
		arp.addMapping("bus_product_group", "id", ProductGroup.class);
		arp.addMapping("bus_product_img", "id", ProductImg.class);
		arp.addMapping("bus_product_type", "id", ProductType.class);
		arp.addMapping("u_user", "id", User.class);
	}
}

