package com.fruit.manage.model;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.fruit.manage.model.base.BaseBanner;
import com.fruit.manage.util.DataResult;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Banner extends BaseBanner<Banner> {
	public static final Banner dao = new Banner().dao();
	
	private Logger log = Logger.getLogger(getClass());
	
	/**
	 * 分页获取数据
	 * @param type
	 * @param gameId
	 * @param startTime
	 * @param endTime
	 * @param pageNum
	 * @param pageSize
	 * @param orderBy
	 * @param isASC
	 * @return
	 */
	public Page<Banner> getData(String groupKey, String key, int pageNum, int pageSize, String orderBy, boolean isASC){
		List<Object> params = new ArrayList<Object>();
		StringBuffer sql = new StringBuffer();
		sql.append("from b_banner where 1=1 ");
		if(StrKit.notBlank(groupKey)){
			sql.append("and group_key = ? ");
			params.add(groupKey);
		}
		if(StrKit.notBlank(key)){
			sql.append("and key = ? ");
			params.add(key);
		}
		orderBy = StrKit.isBlank(orderBy)?"sort":orderBy;
		sql.append("order by "+orderBy+" "+(isASC?"":"desc "));
		
		return paginate(pageNum, pageSize, "select * ", sql.toString(), params.toArray());
	}
	
	/**
	 * 删除数据
	 */
	public DataResult<Object> delete(String[] ids){
		if(ids == null || ids.length == 0){
			return new DataResult<>("没有符合条件的数据可删除");
		}
		log.info("删除数据：ids="+StrKit.join(ids));
		
		List<Object> params = new ArrayList<>();
		StringBuffer sqlParams = new StringBuffer();
		for(String id : ids){
			if(StrKit.isBlank(id)){
				continue;
			}
			params.add(id);
			sqlParams.append("?,");
		}
		if(params.size() == 0){
			return new DataResult<>("没有符合条件的数据可删除");
		}
		sqlParams.deleteCharAt(sqlParams.length() - 1);
		int changeRow = Db.update("delete from b_banner where id in ("+sqlParams.toString()+")", params.toArray());
		log.info("删除数据成功："+changeRow);
		return DataResult.getSuccessData(null);
	}
	
}
