package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseBusinessAuth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessAuth extends BaseBusinessAuth<BusinessAuth> {
	public static final BusinessAuth dao = new BusinessAuth().dao();
}
