package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseBusinessInfo;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessInfo extends BaseBusinessInfo<BusinessInfo> {
    public static final BusinessInfo dao = new BusinessInfo().dao();

    public Page<BusinessInfo> getData(int pageNum, int pageSize, String orderBy, boolean isASC) {
        List<Object> params = new ArrayList<Object>();
        StringBuffer sql = new StringBuffer();
        String select = "SELECT buser.id,buser.phone,binfo.business_name,binfo.address_province,binfo.address_city,binfo.address_shop,binfo.address_detail,auser.`name` AS sales_name,auser.phone AS asles_phone,buser.create_time ";
        sql.append("FROM a_user auser JOIN b_business_user buser ON buser.a_user_sales_id = auser.id JOIN b_business_info binfo ON binfo.u_id = buser.id ");
//        if(StrKit.notBlank(groupKey)){
//            sql.append("and group_key = ? ");
//            params.add(groupKey);
//        }
//        if(StrKit.notBlank(key)){
//            sql.append("and key = ? ");
//            params.add(key);
//        }
        orderBy = StrKit.isBlank(orderBy) ? "sort" : orderBy;
        sql.append("ORDER BY " + orderBy + " " + (isASC ? "" : "DESC "));
        System.out.println("sql:" + sql.toString());
        return paginate(pageNum, pageSize, select, sql.toString());
    }
}
