package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseBusinessUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BusinessUser extends BaseBusinessUser<BusinessUser> {
	public static final BusinessUser dao = new BusinessUser().dao();
}
