package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseCartProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CartProduct extends BaseCartProduct<CartProduct> {
	public static final CartProduct dao = new CartProduct().dao();
}
