package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseCheckInventoryDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckInventoryDetail extends BaseCheckInventoryDetail<CheckInventoryDetail> {
	public static final CheckInventoryDetail dao = new CheckInventoryDetail().dao();
}
