package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseCheckInventory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CheckInventory extends BaseCheckInventory<CheckInventory> {
	public static final CheckInventory dao = new CheckInventory().dao();
}
