package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseClassify;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classify extends BaseClassify<Classify> {
	public static final Classify dao = new Classify().dao();
}
