package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseInventoryRecords;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InventoryRecords extends BaseInventoryRecords<InventoryRecords> {
	public static final InventoryRecords dao = new InventoryRecords().dao();
}
