package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseLogisticsInfo;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsInfo extends BaseLogisticsInfo<LogisticsInfo> {
	public static final LogisticsInfo dao = new LogisticsInfo().dao();

	/**
	 * 根据订单ID删除物流信息表
	 * @param orderID
	 * @return
	 */
	public boolean delLogisticsInfoByOrderID(String orderID){
		String sql ="DELETE from b_logistics_info where order_id=?";
		if(Db.update(sql,orderID)>0){
			return true;
		}
		return  false;
	}

	/**
	 * 根据订单编号获取物流信息表
	 * @param orderId
	 * @return
	 */
	public LogisticsInfo getLogisticeInfoByOrderID(String orderId){
		String sql = "select li.id,li.send_goods_total_cost,li.order_id from b_logistics_info li " +
				"where li.order_id=?";
		return findFirst(sql,orderId);
	}
}
