package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseLogisticsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LogisticsInfo extends BaseLogisticsInfo<LogisticsInfo> {
	public static final LogisticsInfo dao = new LogisticsInfo().dao();
}
