package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseNewtable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newtable extends BaseNewtable<Newtable> {
	public static final Newtable dao = new Newtable().dao();
}
