package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOrderLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLog extends BaseOrderLog<OrderLog> {
	public static final OrderLog dao = new OrderLog().dao();
}
