package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOrderBreakageImg;
import com.jfinal.plugin.activerecord.Db;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderBreakageImg extends BaseOrderBreakageImg<OrderBreakageImg> {
	public static final OrderBreakageImg dao = new OrderBreakageImg().dao();

	/**
	 * 根据报损编号删除报损关联的图片
	 * @param breakageId
	 */
	public void delOrderBreakageImgByBreakageId(Integer breakageId) {
		String sql = "DELETE from b_order_breakage_img where breakage_id = ? ";
		Db.update(sql, breakageId);
	}

	/**
	 * 获取订单报损图片
	 * @param breakageId
	 * @return
	 */
	public List<OrderBreakageImg> getOrderBreakageImgByBreakageId(Integer breakageId) {
		String sql = "SELECT * from b_order_breakage_img where breakage_id=?";
		return find(sql, breakageId);
	}
}
