package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOrderBreakage;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderBreakage extends BaseOrderBreakage<OrderBreakage> {
	public static final OrderBreakage dao = new OrderBreakage().dao();

	/**
	 * 根据订单编号和商品规格编号获取商品报损数据
	 * @param orderId
	 * @param productStandardId
	 * @return
	 */
	public OrderBreakage getOrderBreakageInfoByOrderIdAndPSId(String orderId, Integer productStandardId) {
		String sql = "SELECT * from b_order_breakage where order_id =? and product_standard_id =?";
		return dao.findFirst(sql, orderId, productStandardId);
	}
}
