package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOrderLog;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderLog extends BaseOrderLog<OrderLog> {
	public static final OrderLog dao = new OrderLog().dao();

	/**
	 * 根据时间段更新订单日志的统计
	 * @param createTimes
	 */
	public void updateOrderLog(String[] createTimes) {
		String sql = "update b_order_log ol set ol.is_statistical=0 where ol.create_time BETWEEN ? and ? ";
		Db.update(sql, createTimes[0], createTimes[1]);
	}
}
