package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOutWarehouseDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OutWarehouseDetail extends BaseOutWarehouseDetail<OutWarehouseDetail> {
	public static final OutWarehouseDetail dao = new OutWarehouseDetail().dao();
}
