package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOutWarehouse;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import org.apache.commons.lang3.ArrayUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OutWarehouse extends BaseOutWarehouse<OutWarehouse> {
	public static final OutWarehouse dao = new OutWarehouse().dao();

	/**
	 * 获取数据
	 * @param pageNum
	 * @param pageSize
	 * @param orderBy
	 * @param isASC
	 * @param createTime
	 * @param outWarehouse
	 * @return
	 */
	public Page<OutWarehouse> getData(int pageNum, int pageSize, String orderBy, boolean isASC, String[] createTime, OutWarehouse outWarehouse) {
		List<Object> params = new ArrayList<Object>();
		StringBuffer sql = new StringBuffer();
		sql.append("FROM b_out_warehouse AS ow WHERE 1 = 1 ");


		if (ArrayUtils.isNotEmpty(createTime) && createTime.length == 2) {
			sql.append("and ow.create_time BETWEEN ? and ? ");
			params.add(createTime[0] + " 00:00:00");
			params.add(createTime[1] + " 23:59:59");
		}
		orderBy = StrKit.isBlank(orderBy) ? "ow.create_time" : orderBy;
		sql.append("order by " + orderBy + " " + (isASC ? "" : "desc "));

		String selectStr = "SELECT\n" +
				"\tow.id,\n" +
				"\tow.out_num,\n" +
				"\tow.out_type_num,\n" +
				"\tow.out_total_price,\n" +
				"\tow.out_type,\n" +
				"\tow.warehouse_address,\n" +
				"\tow.out_time,\n" +
				"\tow.create_time,\n" +
				"\tow.update_time ";

		System.out.println(selectStr + sql.toString());
		return paginate(pageNum, pageSize, selectStr, sql.toString(), params.toArray());
	}


}
