package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOutWarehouse;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Page;
import org.apache.commons.lang3.ArrayUtils;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OutWarehouse extends BaseOutWarehouse<OutWarehouse> {
	public static final OutWarehouse dao = new OutWarehouse().dao();

	/**
	 * 获取数据
	 * @param pageNum
	 * @param pageSize
	 * @param orderBy
	 * @param isASC
	 * @param createTime
	 * @param outWarehouse
	 * @return
	 */
	public Page<OutWarehouse> getData(int pageNum, int pageSize, String orderBy, boolean isASC, String[] createTime, OutWarehouse outWarehouse) {
		List<Object> params = new ArrayList<Object>();
		StringBuffer sql = new StringBuffer();
		sql.append("FROM b_out_warehouse AS ow WHERE 1 = 1 ");


		if (ArrayUtils.isNotEmpty(createTime) && createTime.length == 2) {
			sql.append("and ow.order_cycle_date BETWEEN ? and ? ");
			params.add(createTime[0]);
			params.add(createTime[1]);
		}
		orderBy = StrKit.isBlank(orderBy) ? "ow.order_cycle_date" : orderBy;
		sql.append("order by " + orderBy + " " + (isASC ? "" : "desc "));

		String selectStr = "SELECT\n" +
				"\tow.id,\n" +
				"\tow.out_num,\n" +
				"\tow.out_type_num,\n" +
				"\tow.out_total_price,\n" +
				"\tow.out_type,\n" +
				"\tow.warehouse_address,\n" +
				"\tow.out_time,\n" +
				"\tow.order_cycle_date,\n" +
				"\tow.create_time,\n" +
				"\tow.update_time ";

		System.out.println(selectStr + sql.toString());
		return paginate(pageNum, pageSize, selectStr, sql.toString(), params.toArray());
	}


	/**
	 * 根据orderCycleDate获取当天的出库单
	 * @param orderCycleDateStr 订单周期时间字符串
	 * @return 出货单
	 */
	public OutWarehouse getOutWarehouseByOrderCycleDate(String orderCycleDateStr) {
		return findFirst("select * from b_out_warehouse where order_cycle_date = ? ", orderCycleDateStr);
	}

	/**
	 * 添加出库表
	 * @return
	 */
	public OutWarehouse addOutWarehouse(String warehouseAddress, Integer outType, Date orderCycleDate, Integer outTypeNum, Date outTime, BigDecimal outTotalPrice, Integer outNum) {
		OutWarehouse outWarehouse = new OutWarehouse();
		outWarehouse.setOutType(outType);
		outWarehouse.setOutTime(outTime);
		outWarehouse.setOutTotalPrice(outTotalPrice);
		outWarehouse.setOutNum(outNum);
		outWarehouse.setOutTypeNum(outTypeNum);
		outWarehouse.setWarehouseAddress(warehouseAddress);
		outWarehouse.setOrderCycleDate(orderCycleDate);
		outWarehouse.setCreateTime(new Date());
		outWarehouse.setUpdateTime(new Date());
		outWarehouse.save();
		return outWarehouse;
	}
}
