package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseOutWarehouse;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OutWarehouse extends BaseOutWarehouse<OutWarehouse> {
	public static final OutWarehouse dao = new OutWarehouse().dao();
}
