package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseParam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Param extends BaseParam<Param> {
	public static final Param dao = new Param().dao();
}
