package com.fruit.manage.model;

import com.fruit.manage.model.base.BasePayOrderInfo;
import com.jfinal.plugin.activerecord.Db;

import java.math.BigDecimal;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PayOrderInfo extends BasePayOrderInfo<PayOrderInfo> {
	public static final PayOrderInfo dao = new PayOrderInfo().dao();

	/**
	 * 根据订单编号获取真实总共支付的金额
	 * @param orderId
	 * @return
	 */
	public Double getReallyPayMoney(String orderId) {
		String sql = "SELECT sum(poi.pay_the_money) as reallyPayMoney from b_pay_order_info poi where 1=1 and order_id = ?";
		return Db.queryDouble(sql, orderId);
	}

	/**
	 * 根据订单编号获取真实总共支付的金额
	 * @param orderId
	 * @return
	 */
	public Double getPayAllMoney(String orderId) {
		String sql = "SELECT o.pay_total_money from b_order o where o.order_id = ? ";
		return Db.queryDouble(sql, orderId);
	}

	/**
	 * 根据订单编号获取支付的订单信息
	 * @param orderId
	 * @return
	 */
	public List<PayOrderInfo> getPayOrderInfoByOrderId(String orderId) {
		String sql = "SELECT poi.id,poi.pay_of_type,poi.pay_of_time,poi.pay_the_money,poi.pay_of_evidence,poi.user_id,poi.sale_id,poi.order_id,poi.create_time from b_pay_order_info poi where order_id = ?";
		return find(sql, orderId);
	}
}
