package com.fruit.manage.model;

import java.util.List;

import com.fruit.manage.model.base.BasePermission;
import com.jfinal.plugin.activerecord.Db;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permission extends BasePermission<Permission> {
	public static final Permission dao = new Permission().dao();

	/**
	 * 根据角色id查询对应的权限列表
	 * @param roleId
	 * @return
	 */
	public List<Permission> getPermissionByRoleId(int roleId) {
		return find("SELECT p.* FROM `a_role` r, `a_role_permission` rp, `a_permission` p WHERE r.`id` = rp.`role_id` AND p.`id` = rp.`permission_id` AND r.`id` = ?", roleId);
	}
	
	/**
	 * 查询所有权限列表
	 * @return
	 */
	public List<String> getPermissionList() {
		return Db.query("SELECT permission_name from `a_permission`");
	}

	/**
	 * 根据角色id查询对应的权限id列表
	 * @param roleId
	 * @return
	 */
	public List<Integer> getPermissionIdsByRoleId(int roleId) {
		return Db.query("SELECT p.id FROM `a_role` r, `a_role_permission` rp, `a_permission` p WHERE r.`id` = rp.`role_id` AND p.`id` = rp.`permission_id` AND r.`id` = ?", roleId);
	}
}
