package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProcurementPlanDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProcurementPlanDetail extends BaseProcurementPlanDetail<ProcurementPlanDetail> {
	public static final ProcurementPlanDetail dao = new ProcurementPlanDetail().dao();
}
