package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProcurementQuota;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProcurementQuota extends BaseProcurementQuota<ProcurementQuota> {
	public static final ProcurementQuota dao = new ProcurementQuota().dao();
}
