package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImg extends BaseProductImg<ProductImg> {
	public static final ProductImg dao = new ProductImg().dao();
}
