package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductStandard;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductStandard extends BaseProductStandard<ProductStandard> {
	public static final ProductStandard dao = new ProductStandard().dao();

	public List<ProductStandard> list(int productId) {
		return find("SELECT * FROM b_product_standard WHERE product_id=?", productId);
	}
}
