package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductMarket;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;

import java.sql.SQLException;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductMarket extends BaseProductMarket<ProductMarket> {
	public static final ProductMarket dao = new ProductMarket().dao();

	public ProductMarket getMarket(int productId) {
		return findFirst("select * from b_product_market where product_id=? limit 1", productId);
	}

	public boolean save(ProductMarket productMarket, String[] imgs) {
		return Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				boolean result = false;
				productMarket.setUpdateTime(new Date());
				if(productMarket.getId() == null) {
					productMarket.setCreateTime(new Date());
					result = productMarket.save();
				} else {
					result = productMarket.update();
				}
				if(!result) {
					return result;
				}
				result = ProductImg.dao.saveProductImg(true, productMarket.getProductId(), 2, imgs);
				if(!result) {
					return false;
				}
				return true;
			}
		});
	}
}
