package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductMarket;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductMarket extends BaseProductMarket<ProductMarket> {
	public static final ProductMarket dao = new ProductMarket().dao();
}
