package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductKeyword;
import com.fruit.manage.util.Common;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductKeyword extends BaseProductKeyword<ProductKeyword> {
	public static final ProductKeyword dao = new ProductKeyword().dao();

	public List<String> getProductKeyword(int productId) {
		List<ProductKeyword> list = find("select keyword from b_product_keyword where product_id=?", productId);
		List<String> keywords = new ArrayList<>();
		for(ProductKeyword kw : list) {
			keywords.add(kw.getKeyword());
		}
		return keywords;
	}

	public boolean saveProductKeyword(boolean delete, int productId, String[] keyword) {
		return Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				if(delete) {
					Db.update("delete from b_product_keyword where product_id=?", productId);
				}
				List<Object[]> params = new ArrayList<>();
				for(String keyword : keyword) {
					params.add(new Object[]{productId, keyword});
				}
				String sql = "insert into b_product_keyword(product_id, keyword, create_time) values(?,?,now())";
				Db.batch(sql, Common.listTo2Array(params), params.size());
				return true;
			}
		});
	}
}
