package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductKeyword;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductKeyword extends BaseProductKeyword<ProductKeyword> {
	public static final ProductKeyword dao = new ProductKeyword().dao();
}
