package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductType extends BaseProductType<ProductType> {
	public static final ProductType dao = new ProductType().dao();
}
