package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductGroup;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductGroup extends BaseProductGroup<ProductGroup> {
	public static final ProductGroup dao = new ProductGroup().dao();
}
