package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseProductImg;
import com.fruit.manage.util.Common;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.IAtom;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ProductImg extends BaseProductImg<ProductImg> {
	public static final ProductImg dao = new ProductImg().dao();

	public List<ProductImg> getProductImg(int productId, int type) {
		return find("select img_url from b_product_img where product_id=? and type=? order by sort", productId, type);

//		List<ProductImg> list = find("select img_url from b_product_img where product_id=? and type=? order by sort", productId, type);
//		String[] imgs = new String[list.size()];
//		for(int i = 0; i < list.size(); i++) {
//			imgs[i] = list.get(i).getImgUrl();
//		}
//		return imgs;
	}

	/**
	 *	保存商品图片
	 * @param delete	是否按照productId，type删除之前已有的数据
	 * @param productId
	 * @param type
	 * @param imgs
	 * @return
	 */
	public boolean saveProductImg(boolean delete, int productId, int type, String[] imgs) {
		return Db.tx(new IAtom() {
			@Override
			public boolean run() throws SQLException {
				if(delete) {
					Db.update("delete from b_product_img where product_id=? and type=?", productId, type);
				}
				List<Object[]> params = new ArrayList<>();
				int startSort = 1;
				for(String img : imgs) {
					params.add(new Object[]{productId, type, startSort, img});
					startSort++;
				}
				String sql = "insert into b_product_img(product_id, type, sort, img_url, create_time, update_time) values(?,?,?,?,now(),now())";
				Db.batch(sql, Common.listTo2Array(params), params.size());
				return true;
			}
		});
	}
}
