package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseRoleMenu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleMenu extends BaseRoleMenu<RoleMenu> {
	public static final RoleMenu dao = new RoleMenu().dao();
}
