package com.fruit.manage.model;

import java.util.List;

import com.fruit.manage.model.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role().dao();

	/**
	 * 根据用户用户uid查询用户角色列表
	 * @param uid
	 * @return
	 */
	public List<Role> getRoleByUid(int uid) {
		return find("SELECT r.* FROM `a_user` u, `a_user_role` ur, `a_role` r WHERE u.`id` = ur.`user_id` AND r.`id` = ur.`role_id` AND u.`id` = ?", uid);
	}
}
