package com.fruit.manage.model;

import java.util.ArrayList;
import java.util.List;

import org.apache.log4j.Logger;

import com.fruit.manage.model.base.BaseTypeGroup;
import com.fruit.manage.util.Common;
import com.fruit.manage.util.DataResult;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TypeGroup extends BaseTypeGroup<TypeGroup> {
	public static final TypeGroup dao = new TypeGroup().dao();
	
	private Logger log = Logger.getLogger(getClass());
	
	/**
	 * 分页获取数据
	 * @param name
	 * @param pageNum
	 * @param pageSize
	 * @param orderBy
	 * @param orderType
	 * @return
	 */
	public Page<TypeGroup> getData(int pageNum, int pageSize, String name, String orderBy, String orderType){
		List<Object> params = new ArrayList<Object>();
		StringBuffer sql = new StringBuffer();
		sql.append("from b_type_group where 1=1 ");
		if(StrKit.notBlank(name)){
			sql.append("and name like '" + Common.queryLike(name)+"' ");
		}
		orderBy = StrKit.isBlank(orderBy)?"sort":orderBy;
		boolean isASC = "ascending".equals(orderType);
		sql.append("order by "+orderBy+" "+(isASC?"":"desc "));
		return paginate(pageNum, pageSize, "select * ", sql.toString(), params.toArray());
	}
	
	/**
	 * 批量更新状态
	 * @param ids
	 * @param status
	 * @return
	 */
	public DataResult<Object> changeStatus(String[] ids, int status){
		if(ids == null || ids.length == 0){
			return new DataResult<>("没有符合条件的数据可更新");
		}
		log.info("修改分类标签状态：ids="+StrKit.join(ids)+",status="+status);
		List<Object> params = new ArrayList<>();
		params.add(status);
		StringBuffer sqlParams = new StringBuffer();
		for(String id : ids){
			if(StrKit.isBlank(id)){
				continue;
			}
			params.add(id);
			sqlParams.append("?,");
		}
		if(params.size() <= 1){
			return new DataResult<>("没有符合条件的数据可更新");
		}
		sqlParams.deleteCharAt(sqlParams.length() - 1);
		int changeRow = Db.update("update b_type_group set status=?,update_time=now() where id in ("+sqlParams.toString()+")", params.toArray());
		log.info("修改分类标签状态成功："+changeRow);
		return DataResult.getSuccessData(null);
	}
}
