package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseWarehouseLog;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import org.apache.commons.lang3.ArrayUtils;

import java.util.ArrayList;
import java.util.Map;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarehouseLog extends BaseWarehouseLog<WarehouseLog> {
	public static final WarehouseLog dao = new WarehouseLog().dao();

	/**
	 * 获取带条件的分页查询
	 * @param pageNum
	 * @param pageSize
	 * @param orderBy
	 * @param isASC
	 * @param map
	 * @return
	 */
	public Page<WarehouseLog> getAllInfo(int pageNum, int pageSize, String orderBy, boolean isASC, Map map){
		ArrayList<Object> params = new ArrayList<Object>();
		String selectStr = "SELECT wl.id,wl.user_id,wl.product_standard_id,wl.user_type,wl.change_type,wl.change_type,wl.is_statistical,wl.create_time";
		StringBuilder sql=new StringBuilder();
		sql.append("from b_warehouse_log wl where 1=1 ");

		if(StrKit.notBlank((String) map.get("productName"))){
			sql.append("and wl.product_name like ? ");
			params.add("%"+map.get("productName")+"%");
		}
		if(StrKit.notBlank((String)map.get("productId"))){
			sql.append("and wl.product_id like ? ");
			params.add("%"+map.get("productId")+"%");
		}
		if(StrKit.notBlank((String)map.get("productStandardName"))){
			sql.append("and wl.product_standard_name like ? ");
			params.add("%"+map.get("productStandardName")+"%");
		}
		if(StrKit.notBlank((String)map.get("productStandardId"))){
			sql.append("and wl.product_standard_id like ? ");
			params.add("%"+map.get("productStandardId")+"%");
		}

		orderBy = StrKit.isBlank(orderBy) ? "wl.create_time" : orderBy;
		sql.append("order by " + orderBy + " " + (isASC ? "" : "desc "));
		return paginate(pageNum, pageSize, selectStr, sql.toString(), params.toArray());
	}

	/**
	 * 根据change_type(0:入库，1：出库)和时间获取总量
	 * @param change_type
	 * @return
	 */
	public Integer getCountInventorySum(String change_type,String startTime,String endTime){
		String sql="select sum(wl.change_num) from b_warehouse_log wl where 1=1 and wl.change_type = ? and wl.create_time BETWEEN ? and ? ";
		return Db.queryInt(sql, change_type, startTime, endTime);
	}
}
