package com.fruit.manage.model;

import com.fruit.manage.model.base.BaseWarehouseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WarehouseLog extends BaseWarehouseLog<WarehouseLog> {
	public static final WarehouseLog dao = new WarehouseLog().dao();
}
