package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProcurementPlan<M extends BaseProcurementPlan<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return getStr("id");
	}

	public void setProcurementId(java.lang.Integer procurementId) {
		set("procurement_id", procurementId);
	}

	public java.lang.Integer getProcurementId() {
		return getInt("procurement_id");
	}

	public void setProductStandardNum(java.lang.Integer productStandardNum) {
		set("product_standard_num", productStandardNum);
	}

	public java.lang.Integer getProductStandardNum() {
		return getInt("product_standard_num");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}

	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public void setWaitStatisticsOrderTotal(java.lang.Integer waitStatisticsOrderTotal) {
		set("wait_statistics_order_total", waitStatisticsOrderTotal);
	}

	public java.lang.Integer getWaitStatisticsOrderTotal() {
		return getInt("wait_statistics_order_total");
	}

	public void setOrderTotal(java.lang.Integer orderTotal) {
		set("order_total", orderTotal);
	}

	public java.lang.Integer getOrderTotal() {
		return getInt("order_total");
	}

	public void setOrderCycleDate(java.util.Date orderCycleDate) {
		set("order_cycle_date", orderCycleDate);
	}

	public java.util.Date getOrderCycleDate() {
		return get("order_cycle_date");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
