package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProduct<M extends BaseProduct<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setGroupId(java.lang.Integer groupId) {
		set("group_id", groupId);
	}

	public java.lang.Integer getGroupId() {
		return getInt("group_id");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPreviewImg(java.lang.String previewImg) {
		set("preview_img", previewImg);
	}

	public java.lang.String getPreviewImg() {
		return getStr("preview_img");
	}

	public void setTaste(java.lang.String taste) {
		set("taste", taste);
	}

	public java.lang.String getTaste() {
		return getStr("taste");
	}

	public void setDes(java.lang.String des) {
		set("des", des);
	}

	public java.lang.String getDes() {
		return getStr("des");
	}

	public void setBuyCount7(java.lang.Integer buyCount7) {
		set("buy_count_7", buyCount7);
	}

	public java.lang.Integer getBuyCount7() {
		return getInt("buy_count_7");
	}

	public void setOriginalPrice(java.math.BigDecimal originalPrice) {
		set("original_price", originalPrice);
	}

	public java.math.BigDecimal getOriginalPrice() {
		return get("original_price");
	}

	public void setRealPrice(java.math.BigDecimal realPrice) {
		set("real_price", realPrice);
	}

	public java.math.BigDecimal getRealPrice() {
		return get("real_price");
	}

	public void setPriceUnit(java.lang.String priceUnit) {
		set("price_unit", priceUnit);
	}

	public java.lang.String getPriceUnit() {
		return getStr("price_unit");
	}

	public void setPlaceOrigin(java.lang.String placeOrigin) {
		set("place_origin", placeOrigin);
	}

	public java.lang.String getPlaceOrigin() {
		return getStr("place_origin");
	}

	public void setBrand(java.lang.String brand) {
		set("brand", brand);
	}

	public java.lang.String getBrand() {
		return getStr("brand");
	}

	public void setMarketTime(java.util.Date marketTime) {
		set("market_time", marketTime);
	}

	public java.util.Date getMarketTime() {
		return get("market_time");
	}

	public void setSuggest(java.lang.String suggest) {
		set("suggest", suggest);
	}

	public java.lang.String getSuggest() {
		return getStr("suggest");
	}

	public void setHot(java.lang.String hot) {
		set("hot", hot);
	}

	public java.lang.String getHot() {
		return getStr("hot");
	}

	public void setSupplyQuantity(java.lang.String supplyQuantity) {
		set("supply_quantity", supplyQuantity);
	}

	public java.lang.String getSupplyQuantity() {
		return getStr("supply_quantity");
	}

	public void setQuality(java.lang.String quality) {
		set("quality", quality);
	}

	public java.lang.String getQuality() {
		return getStr("quality");
	}

	public void setServiceSupport(java.lang.String serviceSupport) {
		set("service_support", serviceSupport);
	}

	public java.lang.String getServiceSupport() {
		return getStr("service_support");
	}

	public void setExtraDes(java.lang.String extraDes) {
		set("extra_des", extraDes);
	}

	public java.lang.String getExtraDes() {
		return getStr("extra_des");
	}

}
