package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLogisticsInfo<M extends BaseLogisticsInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUId(java.lang.Integer uId) {
		set("u_id", uId);
	}

	public java.lang.Integer getUId() {
		return getInt("u_id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setSendGoodsTotalCost(java.math.BigDecimal sendGoodsTotalCost) {
		set("send_goods_total_cost", sendGoodsTotalCost);
	}

	public java.math.BigDecimal getSendGoodsTotalCost() {
		return get("send_goods_total_cost");
	}

	public void setPackageCost(java.math.BigDecimal packageCost) {
		set("package_cost", packageCost);
	}

	public java.math.BigDecimal getPackageCost() {
		return get("package_cost");
	}

	public void setTricycleCost(java.math.BigDecimal tricycleCost) {
		set("tricycle_cost", tricycleCost);
	}

	public java.math.BigDecimal getTricycleCost() {
		return get("tricycle_cost");
	}

	public void setFreightCost(java.math.BigDecimal freightCost) {
		set("freight_cost", freightCost);
	}

	public java.math.BigDecimal getFreightCost() {
		return get("freight_cost");
	}

	public void setTransshipmentCost(java.math.BigDecimal transshipmentCost) {
		set("transshipment_cost", transshipmentCost);
	}

	public java.math.BigDecimal getTransshipmentCost() {
		return get("transshipment_cost");
	}

	public void setPackageNum(java.lang.Integer packageNum) {
		set("package_num", packageNum);
	}

	public java.lang.Integer getPackageNum() {
		return getInt("package_num");
	}

	public void setRealityTakeNum(java.lang.Integer realityTakeNum) {
		set("reality_take_num", realityTakeNum);
	}

	public java.lang.Integer getRealityTakeNum() {
		return getInt("reality_take_num");
	}

	public void setRealitySendNum(java.lang.Integer realitySendNum) {
		set("reality_send_num", realitySendNum);
	}

	public java.lang.Integer getRealitySendNum() {
		return getInt("reality_send_num");
	}

	public void setDeliveryInfo(java.lang.String deliveryInfo) {
		set("delivery_info", deliveryInfo);
	}

	public java.lang.String getDeliveryInfo() {
		return getStr("delivery_info");
	}

	public void setLicensePlateNumber(java.lang.String licensePlateNumber) {
		set("license_plate_number", licensePlateNumber);
	}

	public java.lang.String getLicensePlateNumber() {
		return getStr("license_plate_number");
	}

	public void setBuyPhone(java.lang.String buyPhone) {
		set("buy_phone", buyPhone);
	}

	public java.lang.String getBuyPhone() {
		return getStr("buy_phone");
	}

	public void setBuyAddress(java.lang.String buyAddress) {
		set("buy_address", buyAddress);
	}

	public java.lang.String getBuyAddress() {
		return getStr("buy_address");
	}

	public void setBuyUserName(java.lang.String buyUserName) {
		set("buy_user_name", buyUserName);
	}

	public java.lang.String getBuyUserName() {
		return getStr("buy_user_name");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
	}

	public java.lang.Integer getDeliveryType() {
		return getInt("delivery_type");
	}

	public void setSendGoodsTime(java.util.Date sendGoodsTime) {
		set("send_goods_time", sendGoodsTime);
	}

	public java.util.Date getSendGoodsTime() {
		return get("send_goods_time");
	}

	public void setTakeGoodsTime(java.util.Date takeGoodsTime) {
		set("take_goods_time", takeGoodsTime);
	}

	public java.util.Date getTakeGoodsTime() {
		return get("take_goods_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
