package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePutWarehouse<M extends BasePutWarehouse<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPutNum(java.lang.Integer putNum) {
		set("put_num", putNum);
	}

	public java.lang.Integer getPutNum() {
		return getInt("put_num");
	}

	public void setPutTypeNum(java.lang.Integer putTypeNum) {
		set("put_type_num", putTypeNum);
	}

	public java.lang.Integer getPutTypeNum() {
		return getInt("put_type_num");
	}

	public void setPutTotalPrice(java.math.BigDecimal putTotalPrice) {
		set("put_total_price", putTotalPrice);
	}

	public java.math.BigDecimal getPutTotalPrice() {
		return get("put_total_price");
	}

	public void setPutType(java.lang.Integer putType) {
		set("put_type", putType);
	}

	public java.lang.Integer getPutType() {
		return getInt("put_type");
	}

	public void setWarehouseAddress(java.lang.String warehouseAddress) {
		set("warehouse_address", warehouseAddress);
	}

	public java.lang.String getWarehouseAddress() {
		return getStr("warehouse_address");
	}

	public void setPutTime(java.util.Date putTime) {
		set("put_time", putTime);
	}

	public java.util.Date getPutTime() {
		return get("put_time");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
