package com.fruit.manage.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
	}

	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public void setOrderTime(java.util.Date orderTime) {
		set("order_time", orderTime);
	}

	public java.util.Date getOrderTime() {
		return get("order_time");
	}

	public void setModifyTime(java.util.Date modifyTime) {
		set("modify_time", modifyTime);
	}

	public java.util.Date getModifyTime() {
		return get("modify_time");
	}

	public void setOrderStatus(java.lang.Integer orderStatus) {
		set("order_status", orderStatus);
	}

	public java.lang.Integer getOrderStatus() {
		return getInt("order_status");
	}

	public void setOrderFinishTime(java.util.Date orderFinishTime) {
		set("order_finish_time", orderFinishTime);
	}

	public java.util.Date getOrderFinishTime() {
		return get("order_finish_time");
	}

	public void setOrderAmount(java.math.BigDecimal orderAmount) {
		set("order_amount", orderAmount);
	}

	public java.math.BigDecimal getOrderAmount() {
		return get("order_amount");
	}

	public void setOrderPayAmount(java.math.BigDecimal orderPayAmount) {
		set("order_pay_amount", orderPayAmount);
	}

	public java.math.BigDecimal getOrderPayAmount() {
		return get("order_pay_amount");
	}

	public void setOrderIspay(java.lang.Integer orderIspay) {
		set("order_ispay", orderIspay);
	}

	public java.lang.Integer getOrderIspay() {
		return getInt("order_ispay");
	}

	public void setOrderIsrefund(java.lang.Integer orderIsrefund) {
		set("order_isrefund", orderIsrefund);
	}

	public java.lang.Integer getOrderIsrefund() {
		return getInt("order_isrefund");
	}

	public void setOrderPaySuccessTime(java.util.Date orderPaySuccessTime) {
		set("order_pay_success_time", orderPaySuccessTime);
	}

	public java.util.Date getOrderPaySuccessTime() {
		return get("order_pay_success_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setBuyuserUid(java.lang.Integer buyuserUid) {
		set("buyuser_uid", buyuserUid);
	}

	public java.lang.Integer getBuyuserUid() {
		return getInt("buyuser_uid");
	}

	public void setConsigneePhone(java.lang.String consigneePhone) {
		set("consignee_phone", consigneePhone);
	}

	public java.lang.String getConsigneePhone() {
		return getStr("consignee_phone");
	}

	public void setConsignee(java.lang.String consignee) {
		set("consignee", consignee);
	}

	public java.lang.String getConsignee() {
		return getStr("consignee");
	}

	public void setConsigneeAddress(java.lang.String consigneeAddress) {
		set("consignee_address", consigneeAddress);
	}

	public java.lang.String getConsigneeAddress() {
		return getStr("consignee_address");
	}

	public void setDeliveryTime(java.lang.String deliveryTime) {
		set("delivery_time", deliveryTime);
	}

	public java.lang.String getDeliveryTime() {
		return getStr("delivery_time");
	}

	public void setDeliveryType(java.lang.Integer deliveryType) {
		set("delivery_type", deliveryType);
	}

	public java.lang.Integer getDeliveryType() {
		return getInt("delivery_type");
	}

	public void setSendProductTime(java.util.Date sendProductTime) {
		set("send_product_time", sendProductTime);
	}

	public java.util.Date getSendProductTime() {
		return get("send_product_time");
	}

	public void setGetProductTime(java.util.Date getProductTime) {
		set("get_product_time", getProductTime);
	}

	public java.util.Date getGetProductTime() {
		return get("get_product_time");
	}

	public void setRefundTime(java.util.Date refundTime) {
		set("refund_time", refundTime);
	}

	public java.util.Date getRefundTime() {
		return get("refund_time");
	}

	public void setRefundAmount(java.math.BigDecimal refundAmount) {
		set("refund_amount", refundAmount);
	}

	public java.math.BigDecimal getRefundAmount() {
		return get("refund_amount");
	}

	public void setCancelTime(java.util.Date cancelTime) {
		set("cancel_time", cancelTime);
	}

	public java.util.Date getCancelTime() {
		return get("cancel_time");
	}

	public void setCancelReason(java.lang.String cancelReason) {
		set("cancel_reason", cancelReason);
	}

	public java.lang.String getCancelReason() {
		return getStr("cancel_reason");
	}

	public void setPayFailMsg(java.lang.String payFailMsg) {
		set("pay_fail_msg", payFailMsg);
	}

	public java.lang.String getPayFailMsg() {
		return getStr("pay_fail_msg");
	}

	public void setProductId(java.lang.String productId) {
		set("product_id", productId);
	}

	public java.lang.String getProductId() {
		return getStr("product_id");
	}

	public void setProductName(java.lang.String productName) {
		set("product_name", productName);
	}

	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public void setProductSinglePrice(java.math.BigDecimal productSinglePrice) {
		set("product_single_price", productSinglePrice);
	}

	public java.math.BigDecimal getProductSinglePrice() {
		return get("product_single_price");
	}

	public void setProductSingleNumber(java.lang.Long productSingleNumber) {
		set("product_single_number", productSingleNumber);
	}

	public java.lang.Long getProductSingleNumber() {
		return getLong("product_single_number");
	}

	public void setProductOriginalPrice(java.math.BigDecimal productOriginalPrice) {
		set("product_original_price", productOriginalPrice);
	}

	public java.math.BigDecimal getProductOriginalPrice() {
		return get("product_original_price");
	}

	public void setProductCount(java.lang.Integer productCount) {
		set("product_count", productCount);
	}

	public java.lang.Integer getProductCount() {
		return getInt("product_count");
	}

	public void setProductRemark(java.lang.String productRemark) {
		set("product_remark", productRemark);
	}

	public java.lang.String getProductRemark() {
		return getStr("product_remark");
	}

	public void setProductOnsaleTime(java.util.Date productOnsaleTime) {
		set("product_onsale_time", productOnsaleTime);
	}

	public java.util.Date getProductOnsaleTime() {
		return get("product_onsale_time");
	}

	public void setProductPosition(java.lang.Integer productPosition) {
		set("product_position", productPosition);
	}

	public java.lang.Integer getProductPosition() {
		return getInt("product_position");
	}

	public void setZhifuPlatformWayId(java.lang.Integer zhifuPlatformWayId) {
		set("zhifu_platform_way_id", zhifuPlatformWayId);
	}

	public java.lang.Integer getZhifuPlatformWayId() {
		return getInt("zhifu_platform_way_id");
	}

	public void setZhifuPlatformWayName(java.lang.String zhifuPlatformWayName) {
		set("zhifu_platform_way_name", zhifuPlatformWayName);
	}

	public java.lang.String getZhifuPlatformWayName() {
		return getStr("zhifu_platform_way_name");
	}

	public void setZhifuStrategyId(java.lang.Integer zhifuStrategyId) {
		set("zhifu_strategy_id", zhifuStrategyId);
	}

	public java.lang.Integer getZhifuStrategyId() {
		return getInt("zhifu_strategy_id");
	}

	public void setOrderIp(java.lang.String orderIp) {
		set("order_ip", orderIp);
	}

	public java.lang.String getOrderIp() {
		return getStr("order_ip");
	}

}
